// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('/Users/bixin/Development/Workspace/expo-ble-demo/node_modules/react');
var { Component } = React;
var ReactNative = require('/Users/bixin/Development/Workspace/expo-ble-demo/node_modules/react-native');
var { AppRegistry } = ReactNative;
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('expo-ble-demo', appParameters);
});
var entryPoint = require('/Users/bixin/Development/Workspace/expo-ble-demo/index.js');